### ISSUE TITLE
Unable to open 'test.wasm': Unsupported node in printModule: Elem.

### ISSUE THREAD

**Issue by bitjson** [reklatsmasters/vscode-wasm#5]
In the latest VS Code version 1.22.2, the "Show WebAssembly" function seems to be broken.

When I right click a `test.wasm` file and click `Show WebAssembly`, I get the error:

```
Unable to open 'test.wasm': Unsupported node in printModule: Elem.
```

**Comment by reklatsmasters** [comment]
@bitjson v1.1.0 used [webassemblyjs](https://github.com/xtuc/webassemblyjs) as parser / printer. This issue related to webassemblyjs. I will try to fix this soon.

Sorry for long answer. I missed the notification :(

**Comment by xtuc** [comment]
This has been fixed in webassemblyjs.
